#Site configuration
title: Read
name:  Read Jekyll

# Major section
major1: "Just an incredibly simple responsive template for Jekyll."
major2: "Faucibus sed lobortis aliquam lorem blandit. Lorem eu nunc metus col. Commodo id in arcu ante lorem ipsum sed accumsan erat praesent faucibus commodo ac mi lacus. Adipiscing mi ac commodo. Vis aliquet tortor ultricies non ante erat nunc integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum."


# Social Links
twitter:  username
facebook: username
instagram: username
github: username
email: test@gmail.com

