#Site configuration
title: Read
name:  Read Jekyll
author: Anthony Stark
work:  Developer
year: 2018

# Section1
sec1: "Read Jekyll"
sec2: "Just an incredibly simple responsive template for Jekyll."
sec3: "Faucibus sed lobortis aliquam lorem blandit. Lorem eu nunc metus col. Commodo id in arcu ante lorem ipsum sed accumsan erat praesent faucibus commodo ac mi lacus. Adipiscing mi ac commodo. Vis aliquet tortor ultricies non ante erat nunc integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum."

# Section 2
sec4: "Things I Can Do"
sec5: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer lorem ipsum dolor sit amet."
icont1: "Write all the code"
icont2: "Stack small boxes"
icont3: "Read books and stuff"
icont4: "Drink much coffee"
icont5: "Lightning bolt"
icont6: "Shadow clone technique"

# Section 3
sec6: "A Few Accomplishments"
sec7: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec8: "Possibly broke spacetime"
sec9: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec10: "Terraformed a small moon"
sec11: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec12: "Snapped dark matter in the wild"
sec13: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Social Links
twitter:  username
facebook: username
instagram: username
github: username
email: test@gmail.com

